### ISSUE TITLE
How to display properly image when editing

### ISSUE THREAD

**Issue by sebastianlp** [sescandell/CollectionUploadSample#2]
Hey @sescandell  . Great work. I took this as my base to make my things. But I've the same issue as you, did you find a working solution to display properly the images when editing something?
I can't get it work. Use what I use in config.yml

```
vich_uploader:
    mappings:
        somemapping:
            uri_prefix: /images/some
```

cannot get the correct file path :(
